#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService1
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Student2014-07-24")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertStdntTabela(StdntTabela instance);
    partial void UpdateStdntTabela(StdntTabela instance);
    partial void DeleteStdntTabela(StdntTabela instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::WcfService1.Properties.Settings.Default.Student2014_07_24ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<StdntTabela> StdntTabelas
		{
			get
			{
				return this.GetTable<StdntTabela>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.StdntTabela")]
	public partial class StdntTabela : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Stdnt;
		
		private string _ImieStdnt;
		
		private string _NazwiskoStdnt;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_StdntChanging(int value);
    partial void OnID_StdntChanged();
    partial void OnImieStdntChanging(string value);
    partial void OnImieStdntChanged();
    partial void OnNazwiskoStdntChanging(string value);
    partial void OnNazwiskoStdntChanged();
    #endregion
		
		public StdntTabela()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Stdnt", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Stdnt
		{
			get
			{
				return this._ID_Stdnt;
			}
			set
			{
				if ((this._ID_Stdnt != value))
				{
					this.OnID_StdntChanging(value);
					this.SendPropertyChanging();
					this._ID_Stdnt = value;
					this.SendPropertyChanged("ID_Stdnt");
					this.OnID_StdntChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImieStdnt", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ImieStdnt
		{
			get
			{
				return this._ImieStdnt;
			}
			set
			{
				if ((this._ImieStdnt != value))
				{
					this.OnImieStdntChanging(value);
					this.SendPropertyChanging();
					this._ImieStdnt = value;
					this.SendPropertyChanged("ImieStdnt");
					this.OnImieStdntChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NazwiskoStdnt", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NazwiskoStdnt
		{
			get
			{
				return this._NazwiskoStdnt;
			}
			set
			{
				if ((this._NazwiskoStdnt != value))
				{
					this.OnNazwiskoStdntChanging(value);
					this.SendPropertyChanging();
					this._NazwiskoStdnt = value;
					this.SendPropertyChanged("NazwiskoStdnt");
					this.OnNazwiskoStdntChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
